name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure you're using the correct Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token or your PAT
          publish_dir: ./build  # Ensure this path matches where your build output is located
          publish_branch: gh-pages  # The branch where GitHub Pages is set up
